# Generated by Django 4.0.3 on 2022-07-16 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notice_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminHOD',
            new_name='AdminUser',
        ),
        migrations.RenameModel(
            old_name='Sessions',
            new_name='Session',
        ),
        migrations.RenameModel(
            old_name='Staffs',
            new_name='Staff',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'AdminUser'), (2, 'Staff'), (3, 'Student'), (4, 'Representative')], default=1, max_length=10),
        ),
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='notice_app.course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notice_app.department')),
            ],
        ),
    ]
